src/Material/Elevation.elm, src/Material/LayoutGrid.elm, src/Material/Options.elm
Partially addresses #26 .
This is the start of adding docs for the low hanging fruit :)
Let me know if this looks good and I'll keep going, it's a good way to get more familiar with the library. Happy to contribute some Travis config to get a build running on each commit/PR too so that we can get feedback for new code without docs.
=> Documentation fixes for Elevation, LayoutGrid and Options

demo/Demo/LinearProgress.elm, elm-package.json, src/Material/LinearProgress.elm, src/Material/Theme.elm
* Expose Material.Toolbar
* Add docs for LinearProgress, remove `accent`
* Add docs for Theme
=> Docs + expose missing module

src/Material/List.elm
See https://github.com/material-components/material-components-web/blob/master/CHANGELOG.md#breaking-changes
=> Correct mdc-list-item__text__secondary -> mdc-list-item__secondary-text

src/Material/List.elm
Allows users to build custom render functions, see request in #199
=> Export ListItem type

src/Internal/Options.elm
The collect function reverses the user given order.
=> Emit classes in order user gave them, not the reverse order

src/Internal/List/Implementation.elm, src/Material/List.elm
Allows you to put a radiobutton or such at the beginning of the list.
=> Add graphic class to list

CHANGELOG.md, package-lock.json, package.json, src/Internal/List/Implementation.elm, src/Material/List.elm
There does not seem to be anything new here, mainly scss fixes.
=> Upgrade to Material Components Web 2.2.0

src/Internal/Fab/Implementation.elm
That leads to very odd results.
=> The button should not use the material-icons class

CHANGELOG.md, src/Internal/Chip/Implementation.elm, src/Internal/List/Implementation.elm, src/Internal/Menu/Implementation.elm, src/Internal/Ripple/Implementation.elm, src/Internal/TabBar/Implementation.elm, src/Internal/Toolbar/Implementation.elm
* Update CHANGELOG
* code cleanup
=> 2.3.1 release minor changes

CHANGELOG.md, demo/Demo/Startpage.elm, demo/Demo/Startpage/Svg/DataTable.elm
And add Data Table to demo home page.
=> Announce 3.1.1 in CHANGELOG

src/Internal/List/Implementation.elm
This is perhaps an improvement upon MDC: you do not need to set/maintain the selected index, just setting `activated` on a list item is sufficient.
=> Set tabindex properly when only the activated item has been set

demo/Demo.elm, demo/Demo/Page.elm, src/Internal/List/Implementation.elm, src/Material/Drawer/Dismissible.elm, src/Material/Drawer/Modal.elm, src/Material/Drawer/Permanent.elm, src/Material/List.elm
Also added keyboard navigation to demo drawer as demonstration how this could be implemented.
=> Activated class was no longer properly set.

src/Material/List.elm
=> Clarify use of activated

demo/Demo.elm, src/Internal/List/Implementation.elm, src/Internal/Menu/Implementation.elm, src/Internal/Select/Implementation.elm
* Keyboard focus for select did no longer work.
* Textfield demo did not close menu whe clicking outside menu.
=> v4 select fixes

src/Internal/Helpers.elm, src/Internal/Keyboard.elm, src/Internal/List/Implementation.elm, src/Internal/Options.elm, src/Internal/TabBar/Implementation.elm, src/Internal/TabBar/Model.elm, src/Material/TabBar.elm
- Scrolls properly to last element.
- Added keyboard handling.
=> Scrolling tab bar fixes

CHANGELOG.md, demo/elm.json, elm.json, examples/basic-app/elm.json, examples/hello-world/elm.json, src/Internal/Options.elm, src/Internal/TabBar/Implementation.elm, src/Internal/TabBar/Model.elm, src/Material/TabBar.elm
Code cleanup, and removing code that was unnecessary.
=> TabBar improvements

CHANGELOG.md, README.md, demo/Demo/Chips.elm, src/Internal/Chip/Implementation.elm, src/Internal/Select/Implementation.elm, src/Internal/Slider/Implementation.elm, src/Internal/Slider/Model.elm, src/Material/Chip.elm
Slider fixes, and chip enhancement.
=> More v7 fixes

package-lock.json, package.json, src/Internal/CircularProgress/Implementation.elm
=> Circular progress fix

src/Internal/Slider/Implementation.elm
=> fix: make sure Up does not fire before InteractionStart on mobile

.conform.yaml, CHANGELOG.md, src/Internal/List/Implementation.elm
=> nonInteractive list still had ripples

src/Internal/TextField/Implementation.elm, src/Material/TextField.elm
Important when submitting to an external form
=> feat: add option to set the name field of a text field

src/Internal/List/Implementation.elm, src/Internal/Menu/Implementation.elm
=> Fix menu selection group focus
